# Project information
site_name: React
site_url: https://github.com/studymadara/React
site_author: Viraj Wagh

# Theme
theme:
  name: readthedocs

# Navigation
nav:
  - Welcome:
      - Overview: index.md