amazon:
  dynamodb:
    endpoint: http://localstack:4566/
  aws:
    accesskey: KEYTEST
    secretkey: KEYID


spring:
  profiles:
    active: dev

management:
  endpoint:
    metrics:
      enable: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus


logging:
  level:
    org: DEBUG
