amazon:
  dynamodb:
    endpoint: http://localstack:4566/
  aws:
    accesskey: KEYTEST
    secretkey: KEYID


spring:
  profiles:
    active: dev
  zipkin:
    base-url: http://zipkin:9411
  application:
    name: LOCAL-APP



management:
  endpoint:
    metrics:
      enable: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus


instance:
  database:
    call: true
  error: false


calling:
  service:
    url: http://app-2:8080

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

