global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 500s
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 500s
    static_configs:
      - targets: [ 'app-1:8080' ]
      - targets: [ 'app-2:8080' ]
      - targets: [ 'app-3:8080' ]
      - targets: [ 'app-4:8080' ]
      - targets: [ 'app-5:8080' ]
    basic_auth:
      username: "vira"
      password: "vira"
