name: "Build Release"

on:
  push:
    branches:
      - "master"
    tags:
        - "v*.*.*"


jobs: 
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    #I AM HOPING NOT TO COPY THIS STEPS AGAIN FROM MAIN.YML

    steps:
      - name: Checkout from main branch
        uses: actions/checkout@v2
        
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: 'temurin'

      - name: Bump Version
        id: bump
        uses: nnichols/maven-version-bump-action@v4
        with:
            github-token: ${{ secrets.github_token }}

      - name: Build Maven Project
        run: mvn -B package --file pom.xml

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "${{steps.bump.outputs.version}}"
          prerelease: false
          files: |
            target/*.jar
